version: 2

sphinx:
  configuration: source/conf.py

python:
  version: 3.8
  pip_install: false
  install:
    - requirements: ci/requirements.txt
    - method: setuptools
      path: .

submodules:
  include: all
  recursive: true
