version: 2

sphinx:
  configuration: source/conf.py

python:
  version: 3.8
  install:
    - requirements: ci/requirements.txt
    - method: setuptools
    - path: .

submodules:
  include: all
  recursive: true
