#!/bin/bash

# Download spaCy language models
python3 -m spacy download en_core_web_sm
python3 -m spacy download en_core_web_md
python3 -m spacy download en_core_web_lg
python3 -m spacy download en_core_web_trf

# Set environments for TMC
TMC_DIR=/home/tmc/
TMC_CONFIG_DIR="${HOME}/tmc-config/tmc-tmc_cli_rust"
WORK_DIR=/home/jovyan

# Install TMC
apt-get install -y --no-install-recommends curl
curl -0 https://raw.githubusercontent.com/rage/tmc-cli-rust/main/scripts/install.sh | bash -s x86_64 linux \

# Set download location for exercises
mkdir -p "${TMC_DIR}"
mkdir -p "${TMC_CONFIG_DIR}"
echo "projects-dir = '${WORK_DIR}'" > "${TMC_CONFIG_DIR}/config.toml"

