#!/bin/bash

# Download spaCy language models
python3 -m spacy download en_core_web_sm
python3 -m spacy download en_core_web_md
python3 -m spacy download en_core_web_lg
python3 -m spacy download en_core_web_trf

# Set user
USER $NB_USER

# Set environments for TMC
ENV TMC_DIR=/opt/tmc/
ENV TMC_CONFIG_DIR="${HOME}/tmc-config/tmc-tmc_cli_rust"
ENV WORK_DIR=/home/$NB_USER/work/

# Set working directory to /opt/app
WORKDIR /opt/app

# Set working directory to /opt/tmc
WORKDIR /opt/tmc

# Install TMC
RUN apt-get install -y --no-install-recommends curl \
    && curl -0 https://raw.githubusercontent.com/rage/tmc-cli-rust/main/scripts/install.sh | bash -s x86_64 linux \
    # Set download location for exercises
    && mkdir -p "${TMC_DIR}" \
    && mkdir -p "${TMC_CONFIG_DIR}" \
    && echo "projects-dir = '${WORK_DIR}'" > "${TMC_CONFIG_DIR}/config.toml" \
    && fix-permissions "${HOME}" \
    && fix-permissions "${TMC_DIR}" \
    && apt-get purge -y --auto-remove curl \
    && apt-get clean
